---
title: "stg2_mm"
author: "Siming Yan"
date: "3/18/2021"
output: html_document
---

```{r}
regresults <- read.csv("./ncaam-march-mania-2021_2/MRegularSeasonDetailedResults.csv")
results <- read.csv("./ncaam-march-mania-2021_2/MNCAATourneyDetailedResults.csv")
sub <- read.csv("./ncaam-march-mania-2021_2/MSampleSubmissionStage2.csv")
seeds <- read.csv("./ncaam-march-mania-2021_2/MNCAATourneySeeds.csv")
```

```{r}
seeds$Seed = as.numeric(substring(seeds$Seed,2,3))
### Collect regular season results - double the data by swapping team positions

r1 = regresults[, c("Season", "DayNum", "WTeamID", "WScore", "LTeamID", "LScore", "NumOT", "WFGA", "WAst", "WBlk", "LFGA", "LAst", "LBlk")]
r2 = regresults[, c("Season", "DayNum", "LTeamID", "LScore", "WTeamID", "WScore", "NumOT", "LFGA", "LAst", "LBlk", "WFGA", "WAst", "WBlk")]
names(r1) = c("Season", "DayNum", "T1", "T1_Points", "T2", "T2_Points", "NumOT", "T1_fga", "T1_ast", "T1_blk", "T2_fga", "T2_ast", "T2_blk")
names(r2) = c("Season", "DayNum", "T1", "T1_Points", "T2", "T2_Points", "NumOT", "T1_fga", "T1_ast", "T1_blk", "T2_fga", "T2_ast", "T2_blk")
regular_season = rbind(r1, r2)


### Collect tourney results - double the data by swapping team positions

t1 = results[, c("Season", "DayNum", "WTeamID", "LTeamID", "WScore", "LScore")] %>% mutate(ResultDiff = WScore - LScore)
t2 = results[, c("Season", "DayNum", "LTeamID", "WTeamID", "LScore", "WScore")] %>% mutate(ResultDiff = LScore - WScore)
names(t1) = c("Season", "DayNum", "T1", "T2", "T1_Points", "T2_Points", "ResultDiff")
names(t2) = c("Season", "DayNum", "T1", "T2", "T1_Points", "T2_Points", "ResultDiff")
tourney = rbind(t1, t2)


### Fit GLMM on regular season data (selected march madness teams only) - extract random effects for each team

march_teams = select(seeds, Season, Team = TeamID)
X =  regular_season %>% 
  inner_join(march_teams, by = c("Season" = "Season", "T1" = "Team")) %>% 
  inner_join(march_teams, by = c("Season" = "Season", "T2" = "Team")) %>% 
  select(Season, T1, T2, T1_Points, T2_Points, NumOT) %>% distinct()
X$T1 = as.factor(X$T1)
X$T2 = as.factor(X$T2)

quality = list()
for (season in unique(X$Season)) {
  glmm = glmer(I(T1_Points > T2_Points) ~  (1 | T1) + (1 | T2), data = X[X$Season == season & X$NumOT == 0, ], family = binomial) 
  random_effects = ranef(glmm)$T1
  quality[[season]] = data.frame(Season = season, Team_Id = as.numeric(row.names(random_effects)), quality = exp(random_effects[,"(Intercept)"]))
}
quality = do.call(rbind, quality)


### Regular season statistics

season_summary = 
  regular_season %>%
  mutate(win14days = ifelse(DayNum > 118 & T1_Points > T2_Points, 1, 0),
         last14days = ifelse(DayNum > 118, 1, 0)) %>% 
  group_by(Season, T1) %>%
  summarize(
    WinRatio14d = sum(win14days) / sum(last14days),
    PointsMean = mean(T1_Points),
    PointsMedian = median(T1_Points),
    PointsDiffMean = mean(T1_Points - T2_Points),
    FgaMean = mean(T1_fga), 
    FgaMedian = median(T1_fga),
    FgaMin = min(T1_fga), 
    FgaMax = max(T1_fga), 
    AstMean = mean(T1_ast), 
    BlkMean = mean(T1_blk), 
    OppFgaMean = mean(T2_fga), 
    OppFgaMin = min(T2_fga)  
  )

season_summary_X1 = season_summary
season_summary_X2 = season_summary
names(season_summary_X1) = c("Season", "T1", paste0("X1_",names(season_summary_X1)[-c(1,2)]))
names(season_summary_X2) = c("Season", "T2", paste0("X2_",names(season_summary_X2)[-c(1,2)]))


### Combine all features into a data frame

data_matrix =
  tourney %>% 
  left_join(season_summary_X1, by = c("Season", "T1")) %>% 
  left_join(season_summary_X2, by = c("Season", "T2")) %>%
  left_join(select(seeds, Season, T1 = TeamID, Seed1 = Seed), by = c("Season", "T1")) %>% 
  left_join(select(seeds, Season, T2 = TeamID, Seed2 = Seed), by = c("Season", "T2")) %>% 
  mutate(SeedDiff = Seed1 - Seed2) %>%
  left_join(select(quality, Season, T1 = Team_Id, quality_march_T1 = quality), by = c("Season", "T1")) %>%
  left_join(select(quality, Season, T2 = Team_Id, quality_march_T2 = quality), by = c("Season", "T2"))


### Prepare xgboost 

features = setdiff(names(data_matrix), c("Season", "DayNum", "T1", "T2", "T1_Points", "T2_Points", "ResultDiff"))
dtrain = xgb.DMatrix(as.matrix(data_matrix[, features]), label = data_matrix$ResultDiff)

train_mym  = data_matrix[, features]
traget_mym = data_matrix$ResultDiff
```

```{r}
mmassey = read.csv("./ncaam-march-mania-2021_2/MMasseyOrdinals.csv")
ordinals_df=mmassey
# ordinals_df %>% names()
ordinals_df = ordinals_df %>% group_by(SystemName,Season,TeamID) %>% filter(row_number() == 1L)
ordinals_df['Rating']= 100-4*log(ordinals_df['OrdinalRank']+1)-ordinals_df['OrdinalRank']/22
ordinals_df = ordinals_df[ordinals_df$SystemName=="POM", ]
names(ordinals_df)[2] = "DayNum"

ordinals_df = ordinals_df[,!names(ordinals_df) %in% c("SystemName", "OrdinalRank", "DayNum")]
names(ordinals_df)[2] = "T1"
# ordinals_df %>% names()
# ordinals_df[ordinals_df$DayNum == 137,]
data_matrix_ad = merge(data_matrix, ordinals_df, by = c("Season","T1"))
names(ordinals_df)[2] = "T2"
data_matrix_ad = merge(data_matrix_ad, ordinals_df, by = c("Season","T2"))
```

```{r}
features = setdiff(names(data_matrix_ad), c("Season", "DayNum", "T1", "T2", "T1_Points", "T2_Points", "ResultDiff"))
# features
train_data_my  = data_matrix_ad[, features]
train_label_my = data_matrix_ad$ResultDiff



train_label_my = train_label_my %>% data.frame()
names(train_label_my) = "train_label_my"
train_label_my = train_label_my %>% mutate(train_label_my =ifelse(train_label_my > 0, "win", "loss"))
# train_label_my %>% table
train_label_my  = train_label_my$train_label_my %>% as.factor()

# train_label_my
```

```{r}
trControl = trainControl(
    method = 'cv',
    number = 10,
    # summaryFunction = giniSummary,
    classProbs = TRUE,
    verboseIter = TRUE,
    allowParallel = TRUE)

tuneGridXGB <- expand.grid( #500	3	0.05	5	0.8	25	0.8
    nrounds = c(475),
    max_depth = c(3, 4), 
    eta = c(0.045),
    gamma = c(3),
    colsample_bytree = c(.8),
    subsample = c(0.750),
    min_child_weight = c(12, 15),
    rate_drop = c(.2),
    skip_drop = c(.3))
```

```{r}
library(doParallel)
cl <- makePSOCKcluster(8)
registerDoParallel(cl)
# stopCluster(cl)
# save.image("./based_tune_caret.RData")
```

```{r}
start <- Sys.time()

# train the xgboost learner
xgbmod <- train(
    x = train_data_my,
    y = train_label_my,
    method = 'xgbDART',
    metric = "Accuracy",
    # metric = 'NormalizedGini',
    trControl = trControl,
    tuneGrid = tuneGridXGB,
    verbose = T)


print(Sys.time() - start)
xgbmod#500	4	0.05	10	0.9	40	0.75

```



#--------------------------------------------


```{r}
sub$Season = as.numeric(substring(sub$ID,1,4))
sub$T1 = as.numeric(substring(sub$ID,6,9))
sub$T2 = as.numeric(substring(sub$ID,11,14))

Z = sub %>% 
  left_join(season_summary_X1, by = c("Season", "T1")) %>% 
  left_join(season_summary_X2, by = c("Season", "T2")) %>%
  left_join(select(seeds, Season, T1 = TeamID, Seed1 = Seed), by = c("Season", "T1")) %>% 
  left_join(select(seeds, Season, T2 = TeamID, Seed2 = Seed), by = c("Season", "T2")) %>% 
  mutate(SeedDiff = Seed1 - Seed2) %>%
  left_join(select(quality, Season, T1 = Team_Id, quality_march_T1 = quality), by = c("Season", "T1")) %>%
  left_join(select(quality, Season, T2 = Team_Id, quality_march_T2 = quality), by = c("Season", "T2"))

# Z[, features]
```


```{r}
names(ordinals_df)[2] = "T1"
test_my_ad = merge(Z, ordinals_df, by = c("Season","T1"))
names(ordinals_df)[2] = "T2"
test_my_ad = merge(test_my_ad, ordinals_df, by = c("Season","T2"))
test_my_ad = test_my_ad[, features]
# features
# names(test_my)[!names(test_my) %in% names(train_data_my)]
# names(train_data_my)[!names(train_data_my) %in% names(test_my)]
test_my = test_my_ad[, names(train_data_my)]
# names(test_my)
# names(train_data_my)
test_my
```

```{r}
preds <- predict(xgbmod, newdata = test_my, type = "prob")
preds
sub$Pred = preds$win
sub = sub[,c(1,2)]
sub
# sub$Pred[sub$Pred <= 0.025] = 0.025
# sub$Pred[sub$Pred >= 0.975] = 0.975
write.csv(sub, "./sub_stg2_m_xgbdart.csv", row.names = F)

# .0.49459 no medal

```


```{r}
train_data_my_stg2 = cbind(train_data_my, train_label_my)
# train_label_my
write.csv(train_data_my_stg2 , "./sb/train_m_stg2.csv", row.names = F)
write.csv(test_my , "./sb/test_m_stg2.csv", row.names = F)
```